stages:
 - test

test-server:
  stage: test
  image: python:3.5
  before_script:
    - python3 -m venv server/venv/
    - source server/venv/bin/activate
    - pip install -r server/requirements.txt
  script:
    - echo "Hello world"
