stages:
 - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_DOWNLOAD_CACHE: /cache/pip-dll
  PIP_CACHE_DIR: /cache/pip-cache

test-server:
  stage: test
  image: masashiy/ccg2lambda
  script:
    - make local
  tags:
    - docker
    - debian
    - python
  retry: 2