stages:
 - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_DOWNLOAD_CACHE: /cache/pip-dll
  PIP_CACHE_DIR: /cache/pip-cache

test-server:
  stage: test
  image: masashiy/ccg2lambda
  before_script:
    - coqc ccg2lambda/coqlib.v
    - make ELMO_DOWNLOAD=/cache/elmo
    - cd server
    - python3 -m venv venv/
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r ../depccg/requirements.txt
  script:
    - cd src
    - python3 -m unittest discover
    - pycodestyle --show-source --show-pep8 --statistics --max-line-length=120 --benchmark .
  retry: 1