#Who received both an Oscar and a Nobel Prize?
SELECT DISTINCT ?item ?itemLabel WHERE {
  ?item wdt:P166/wdt:P31? wd:Q7191 .
  ?item wdt:P166/wdt:P31? wd:Q19020 .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
  }
}